# Generated by Django 3.1.7 on 2021-04-20 06:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemName', models.CharField(max_length=100)),
                ('modifierType', models.CharField(max_length=100)),
                ('problem_modifier', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_problem', to='MyDiary.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_knowledge', models.IntegerField()),
                ('rating_behavior', models.IntegerField()),
                ('rating_status', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetName', models.CharField(max_length=100)),
                ('targetDescription', models.CharField(max_length=100)),
                ('targetNote', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_target', to='MyDiary.problem')),
            ],
        ),
        migrations.CreateModel(
            name='SignAndSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomName', models.CharField(max_length=100)),
                ('symptomDescription', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_symptom', to='MyDiary.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('apt', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.date(2021, 3, 3))),
                ('mobile', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
