# Generated by Django 3.1.7 on 2021-04-20 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='modifierType',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_modifier',
        ),
        migrations.AddField(
            model_name='domain',
            name='patient',
            field=models.ForeignKey(default=-999, on_delete=django.db.models.deletion.CASCADE, related_name='list_domain', to='MyDiary.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_target', to='MyDiary.category'),
        ),
        migrations.CreateModel(
            name='patient_evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_category', to='MyDiary.category')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_patient', to='MyDiary.patient')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_problem', to='MyDiary.problem')),
                ('rating_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_rating_scale', to='MyDiary.rating_scale')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_target', to='MyDiary.target')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifierType', models.CharField(max_length=100)),
                ('problem_modifier', models.CharField(max_length=100)),
                ('problems', models.ManyToManyField(to='MyDiary.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='scheme',
            field=models.ForeignKey(default=-99, on_delete=django.db.models.deletion.CASCADE, related_name='list_domain', to='MyDiary.scheme'),
            preserve_default=False,
        ),
    ]
